### ISSUE TITLE
kesalahan saat menuju browse

### ISSUE THREAD

**Issue by cyber12drago** [2018-PemrogramanWeb-B/tugas7-fp-umkmgo#8]
Saat memencet browse maka akan muncul seperti ini (saya sudah instalasi sesuai pentujuk di pdf)

![umkmgo](https://user-images.githubusercontent.com/36811855/50212567-e8b65600-03ad-11e9-884a-42b88952e8c7.jpg)

**Comment by gslayer0** [comment]
Salam UMKM. terimakasih telah mengunjungi web kami. 

silahkan setting file .env seperti yang tertera di powepoint tutorial tambahan, dan lakukan migrasi.

Terimakasih

**Comment by cyber12drago** [comment]
Seperti saya bilang sebelumnya saya sudah mengikuti pentujuk seperti di pdf dan sesuai pdf yang anda maksud. Saya cuman bisa login dan regist tetapi tidak bisa browse.  Terima kasih
